version: '3'

networks:
    trivagoApp:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8000:80"
        links:
            - app
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - app
            - mysql
        networks:
            - trivagoApp

    mysql:
        image: mysql:8.0.34
        container_name: mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "8001:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - trivagoApp
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - ./:/var/www/app
        ports:
            - "9001:9000"
        depends_on:
            - mysql
        networks:
            - trivagoApp
